Minor tweaks for plotting
cms-rwth/CoffeaRunner pull request #19
Opened 2023-05-16 11:31 UTC by andreypz

Just a few changes to make it work on my outputs

2023-05-24 09:30 UTC, Ming-Yan requested changes
Hi @andreypz ,  thanks for the proposed changes, there are some minor changes need to be done then I can merge this PR

2023-05-24 09:30 UTC, Ming-Yan commented on src/BTVNanoCommissioning/utils/plot_utils.py
> +    mins,maxs=0,1
I think the `maxs` should set as default axis range. namely `len(val)-1`

2023-05-24 09:30 UTC, Ming-Yan commented on plotting/comparison.py
> +            denom_fill_opts={},
If we want to change the default with `denom_fill_opts={}`, the [setup](https://github.com/cms-rwth/CoffeaRunner/blob/1ed0d8f08696155bba908984af78051085c8ffca/src/BTVNanoCommissioning/utils/plot_utils.py#L589) in `plot_util.py`  should change to `if denom_fill_opts is not {}:`

2023-05-24 09:30 UTC, Ming-Yan requested changes
Hi @andreypz ,  thanks for the proposed changes, there are some minor changes need to be done then I can merge this PR

2023-05-24 09:30 UTC, Ming-Yan requested changes
Hi @andreypz ,  thanks for the proposed changes, there are some minor changes need to be done then I can merge this PR

2023-06-01 13:22 UTC, andreypz commented on src/BTVNanoCommissioning/utils/plot_utils.py
> +    mins,maxs=0,1
Ok, done

2023-06-01 13:22 UTC, andreypz commented on plotting/comparison.py
> +            denom_fill_opts={},
Ok, changed the plot_utils.py

2023-06-01 14:50 UTC, merged