WIP: Improving plotting scripts
cms-rwth/CoffeaRunner pull request #20
Opened 2023-07-18 14:49 UTC by andreypz

This PR would allow the 'additional_scaling' of multiple samples at the same time. For the moment, this would only work for one sample.

2023-07-18 15:50 UTC, andreypz commented
Also resolved conflicts in the readme file. (But did not check the correctness of the instructions)

2023-07-19 14:32 UTC, andreypz commented
Added a few fixes so that test_wf can run

2023-07-19 15:18 UTC, Ming-Yan requested changes
Thanks @andreypz  for this PR, I just have some minor comments for the fetcher

2023-07-19 15:18 UTC, Ming-Yan commented on filefetcher/fetch.py
Though this not relevant to the changes here, I would suggest modify `xrootd` instead of `root://` since not all protocols contains xrootd but for sure `root://` [L111](https://github.com/cms-rwth/CoffeaRunner/pull/20/files#diff-9d4c5c897385a41c4d08fa255a581a0b96dce52dcbd31c9220cd45ecef644b71R111)

2023-07-19 15:18 UTC, Ming-Yan commented on filefetcher/fetch.py
> +        if Tier not in ["NANOAODSIM", "USER"]:
Probably also `NANOAOD` in the list?

2023-07-27 13:13 UTC, andreypz commented on filefetcher/fetch.py
Implemented

2023-07-27 13:18 UTC, andreypz commented on filefetcher/fetch.py
> +        if Tier not in ["NANOAODSIM", "USER"]:
Actually, after taking another look at his, I remember that the whole point of this particular check is to create a different dataset names for all periods of the data-taking.
For example, using these datasets:
> /DoubleMuon/Run2017B-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
> /DoubleMuon/Run2017C-UL2017_MiniAODv2_NanoAODv9-v1/NANOAOD
We want to create names `DoubleMuon_Run2017B-UL2017_MiniAODv2_NanoAODv9-v1` and `DoubleMuon_Run2017C-UL2017_MiniAODv2_NanoAODv9-v1` using first two parts of the full name (and not just `DoubleMuon` using the first part). I think this is a convention for BTV. But maybe we do not need this for analysis, and should just merge everything into single name.
Anyway, I modified the code now to check for Tier=NANOAOD (that means Data).

2023-07-27 13:20 UTC, merged